ALTER TABLE events
ADD COLUMN amount INTEGER DEFAULT 1 NOT NULL,
ADD COLUMN chance INTEGER DEFAULT 1 NOT NULL,
ADD COLUMN max INTEGER DEFAULT 100 NOT NULL,
ADD COLUMN cooldown INTEGER DEFAULT 1 NOT NULL;

ALTER TABLE destinations
ADD COLUMN chance INTEGER DEFAULT 1 NOT NULL,
ADD COLUMN low INTEGER DEFAULT 1 NOT NULL,
ADD COLUMN max INTEGER DEFAULT 100 NOT NULL,
ADD COLUMN mod_max INTEGER DEFAULT 1 NOT NULL,
ADD COLUMN duration INTEGER DEFAULT 1 NOT NULL;

DROP TABLE treasure;
